defaults: &defaults
  adapter: mysql2
  username: root
  password:

development:
  <<: *defaults
  database: lms_development

test: &test
  <<: *defaults
  database: lms_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *defaults
  database: lms_production


